language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
script:
  - cd website && npm install && npm run build
deploy:
  provider: surge
  project: ./website/build/thorium
  domain: thoriumsim.com
  skip_cleanup: true
